#!/bin/bash

display_en()
{
yad --notification --image=drive-removable-media \
--command=mx-usb-unmounter --text="Unmount Media" \
--menu="List Devices!mx-usb-unmounter!drive-removable-media|Help!mx-viewer mepiscommunity.org!gtk-help|Quit!quit!gtk-quit"
}

LNG=$(locale|grep ^LANG=|cut -f2 -d=|cut -f1 -d_)

case $LNG in

	en) display_en
	;;

esac

