#!/bin/bash

on_click() {
check=$(ps -C mx-usb-unmounter | grep mx-usb-unmount | cut -d " " -f1)
echo $check

if [ "$check" = "" ]; then
	mx-usb-unmounter
else
	kill "$check"
fi

}

display_en() {
yad --notification --image=media-eject \
--command="bash -c on_click" \
--text="Unmount Media" \
--menu="List Devices!mx-usb-unmounter!drive-removable-media|Help!mx-viewer mepiscommunity.org!gtk-help|About!mx-usb-unmounter -h!help-about|Quit!quit!gtk-quit"
}

LNG=$(locale|grep ^LANG=|cut -f2 -d=|cut -f1 -d_)

export -f on_click

case $LNG in

	en) display_en
	;;

	*) display_en
	;;

esac
